print("Please enter the number of lives.")
l = str (input())
print("Please enter the energy level.")
e = str (input())
print("Please enter the shield level.")
sl = str(input())
print("Health has been set.")
print(f"Lives: {l}")
print(f"Energy: {e}")
print(f"Shield: {sl}")