print("Please enter the number of lives.")
l = int (input())
print("Please enter the energy level.")
e = int (input())
print("Please enter the shield level.")
sl = int(input())
print("Health has been set.")
print("Lives:", "\u2665"*l)
print("Energy:","\u2666"*e)
print("Shield: ","\u2666"* sl)